version: 2.1

orbs:
  cypress: cypress-io/cypress@1.19.1

executors:
  cypress-node12-chrome77:
    docker:
      - image: "cypress/browsers:node12.6.0-chrome77"

jobs:
  lint:
    docker:
      - image: circleci/node:10.19
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/
      - checkout
      - run: yarn install
      - run: yarn lint
  jest:
    docker:
      - image: circleci/node:10.19
    working_directory: ~/repo
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn jest

workflows:
  version: 2
  Test_Workflow:
    jobs:
      - cypress/run:
          name: Cypress Tests
          executor: cypress-node12-chrome77
          browser: chrome
          yarn: true
          start: yarn develop
          wait-on: "--timeout 20000 http://localhost:8000"
      - lint:
          requires:
            - Cypress Tests
      # - jest:
      #     requires:
      #       - Cypress Tests
