version: 2.1

orbs:
  cypress: cypress-io/cypress@1.12.0

jobs:
  lint:
    executor: cypress/base-10
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn lint
  Jest:
    docker:
      - image: circleci/node:10.17
    working_directory: ~/repo
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn jest

workflows:
  version: 2
  Test_Workflow:
    jobs:
      - cypress/install:
          name: Cypress Install
          yarn: true
          build: yarn build
      - cypress/run:
          name: Cypress Tests
          requires:
            - Cypress Install
          yarn: true
          start: yarn develop
          wait-on: "--timeout 20000 http://localhost:8000"
      - lint:
          requires:
            - Cypress Tests
#      - Jest
