version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14.17.0
    branches:
      ignore:
        - typescript
    parallelism: 2

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run lint
      - run: yarn lint
      # check types
      - run: yarn tsc
      # run tests!
      - run: yarn test:ci
